# Generated by Django 4.2.18 on 2025-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='receipt_number',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
