# Generated by Django 5.1.3 on 2025-02-06 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_participant_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('fuel', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('entry_marked', models.BooleanField(default=False)),
            ],
        ),
    ]
