# Generated by Django 5.1.3 on 2025-02-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bonusentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusentry',
            old_name='fuel',
            new_name='entries',
        ),
    ]
