# Generated by Django 5.1.3 on 2025-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bonusentry_latitude_bonusentry_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='entry_count',
            field=models.IntegerField(default=0),
        ),
    ]
