# Generated by Django 5.1.3 on 2025-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_participant_latitude_participant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
