# Generated by Django 5.1.3 on 2025-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_participant_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
