# Generated by Django 5.1.3 on 2025-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_participant_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
