# Generated by Django 5.1.3 on 2025-02-08 18:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_participant_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='participant',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
