# Generated by Django 5.1.3 on 2025-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_bonusentry_created_at_participant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
