# Generated by Django 5.1.3 on 2025-02-10 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_bonusentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bonusentry',
            name='date',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
