# Generated by Django 5.1.4 on 2026-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_participant_operator_alter_bonusentry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('entry_count', models.IntegerField(default=0)),
            ],
        ),
    ]
