# Generated by Django 5.1.4 on 2026-01-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_userentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='entry_count',
        ),
    ]
