# Generated by Django 4.2.18 on 2026-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_participant_entry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='litres',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
